### ISSUE TITLE
Pip instalation? 

### ISSUE THREAD

**Issue by EmadAlamoudi** [nalomran/pubmed2doc#1]
Thanks Nawaf for the nice tool. 
Wouldn't be nice to enable installing the library directly through pip without the need to clone github repo?

**Comment by nalomran** [comment]
Hi Emad,

Thank you for your kind words and for providing a feedback as well. I have thought about this before but currently I would leave it the way it is and may upload it to PyPi for the future update. I had the module be tested by different individuals and non have an issue nor difficulty cloning and executing It locally thus far. I am closing this issue for now however I do appreciate the feedback and thanks for dropping in :)
